# .github/workflows/docker-publish.yml
name: Manual Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker tag variable
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t cloudsecnetwork/phishintel:${{ env.TAG }} -t cloudsecnetwork/phishintel:latest .

      - name: Push Docker image (versioned tag)
        run: docker push cloudsecnetwork/phishintel:${{ env.TAG }}

      - name: Push Docker image (latest)
        run: docker push cloudsecnetwork/phishintel:latest
