name: Prepare Release

on:
  release:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: extract-version
        run: |
          # Remove 'v' prefix from tag name
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update VERSION file
        run: |
          echo "${{ steps.extract-version.outputs.version }}" > VERSION

      - name: Update package.json version
        run: |
          npm version ${{ steps.extract-version.outputs.version }} --no-git-tag-version

      - name: Update client package.json version
        run: |
          cd client
          npm version ${{ steps.extract-version.outputs.version }} --no-git-tag-version

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION package.json client/package.json
          git commit -m "Update version to ${{ steps.extract-version.outputs.version }}"
          git push

      - name: Create new tag with updated version
        run: |
          git tag -d ${{ github.ref_name }}
          git push origin :refs/tags/${{ github.ref_name }}
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }} 